### ISSUE TITLE
Kotlin runtime library

### ISSUE THREAD

**Issue by mainrs** [ocpu/Boxlin#2]
I was looking into shadowfact's version of the library and this one. There was a question about the differences between those too. Mind explaining to me what exactly `instance factory methods` are? I couldn't find that many information on the web.

Do I need to bundle the kotlin runtime and reflect library myself or is Boxlin packaging them for me?

**Comment by ocpu** [comment]
In the recent version I bundle Kotlin runtime but not the reflect part. If you require it you would need to include it yourself. I may future include it but no guarantee. But if it is important for everyone I can include it.

Instance factory methods are functions that give out instances of your class. You can construct the instance yourself depending on the situation. What is shown bellow is a basic example of how you would do this. And if you take a look at `net.minecraftforge.fml.common.Loader` it has a version of this.
```kotlin
class Mod {
    private val myInstance = Mod()

    companion object {
        fun instanceFactory() = Mod().myInstance
    }

    fun test() = "hello world"
}
```
or in java
```java
public class Mod {

    private Mod myInstance = new Mod();

    public static Mod instanceFactory() {
        return new Mod().myInstance;
    }
    
    public String test() {
        return "hello world";
    }
}
```
In forge you would tag the instance factory method with `net.minecraftforge.fml.common.Mod.InstanceFactory`. 
```kotlin
import net.minecraftforge.fml.common
// [...]
@Mod.InstanceFactory
fun instanceFactory(): Mod // [...]
```
```java
import net.minecraftforge.fml.common;
// [...]
@Mod.InstanceFactory
public static Mod instanceFactory() // [...]
```

And sorry for the late responce.
